// Each new term in the Fibonacci sequence is generated by 
// adding the previous two terms.By starting with 1 and 2, 
// the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not 
// exceed four million, find the sum of the even - valued terms.

let fibonacci = n => {
    if(n === 1) {
        return 1
    } else if(n === 2) {
        return 2
    } else {
        return fibonacci(n-2) + fibonacci(n-1)
    }
}

let sumfibo = () => {
    let fibolist = []
    for(let i = 1; i <= 32; i++) {
        if(fibonacci(i) % 2 === 0) {
            fibolist.push(fibonacci(i))
        }
    }
    console.log(fibolist.reduce((a,b) => a + b))
}

sumfibo()

// Answer -> 4613732